services:
  database:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/srv/app 
    ports:
      - "8000:8000" 
    depends_on:
      - database
    #   - redis
    #   - rabbitmq
    env_file:
      - .env
    environment:
      DOCKER_WORKDIR: /srv/app
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/srv/app 
    ports:
      - "8080:8080" 
    depends_on:
      - database
      - backend
    env_file:
      - .env
    environment:
      DOCKER_WORKDIR: /srv/app

volumes:
  pgdata: {}
